# ==========================================
# ==     Generate Pull Request Title      ==
# ==========================================
# This action will call a re-usable workflow
# to update Pull Request titles using the
# originating branch name.
#
# Branch name format:
#     type/ticketid-summary
#
# example branch name:
#     feature/PCWEB-123-some-new-nifty-feature
#
# valid "type" values: feature, bug, chore,
#     docs, spike, release
#
# valid "ticketid" prefixes: APPSERV-, CAB-,
#     PCWEB-, PROARCHQE-, PROCAP-, PRODATA-,
#     PROREP-, PROSEARCH-, SINC-, TSE-
# ==========================================


name: generate-pull-request-title

on:
  pull_request:
    branches: [ develop, qa, master, main ]

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: Smarsh/proarch-github-reusable-workflows/.github/workflows/reusable-workflow-generate-pull-request-title.yml@main
