# ==================================================
# ==               Git Secrets Scan               ==
# ==================================================
# This action will call a re-usable workflow
# to scan for "secrets" in your GitHub repo
# using the Git Secrets Scanner project
# found here:
#     https://github.com/Smarsh/Git-Secrets-Scanner
# ==================================================

name: Git-Secrets-Scan

on:
  push:

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: Smarsh/proarch-github-reusable-workflows/.github/workflows/reusable-workflow-git-sercrets-scan.yml@main
    secrets:
      access_token: ${{ secrets.SECRETS_SCANNER_ACCESS_TOKEN }}
